name: flutter_catalog
description: An app showcasing Flutter components, with side-by-side source code view.

# *Note*: when version change, remember to also update constants.dart.
version: 2.5.5+58

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_floatactionbuttons: 0.1.0
  animations: 1.1.2
  async: ^2.4.0
  backdrop: 0.4.6
  cached_network_image: 2.3.2+1
  charts_flutter: 0.9.0
  cloud_firestore: 0.14.0+2
  english_words: 3.1.5
  extended_image: 1.1.2
  firebase_analytics: 6.0.0
  firebase_auth: 0.18.0+1
  firebase_core: 0.5.0
  firebase_database: 4.0.0
  firebase_ml_vision: 0.9.6+2
  firebase_storage: 4.0.0
  flutter_bloc: 6.0.5
  flutter_gallery_assets: 0.1.9+2
  flutter_markdown: 0.4.4
  flutter_webview_plugin: 0.3.11
  fluttertoast: 7.1.1
  google_fonts: 1.1.0
  google_sign_in: 4.5.4
  hive_flutter: 0.3.1
  hive: 1.4.4
  http: 0.12.2
  image_picker: 0.6.7+11
  local_auth: 0.6.3+2
  lottie: 0.6.0
  package_info: 0.4.3
  path_provider: 1.6.18
  path: 1.7.0
  provider: 4.3.2+2
  scoped_model: 1.0.1
  sembast: 2.4.7
  shared_preferences: 0.5.12
  sqflite: 1.3.1+1
  substring_highlight: 0.1.2
  syntax_highlighter: 0.1.1
  transparent_image: 1.0.0
  url_launcher: 5.7.2
  video_player: 0.11.0
  widget_with_codeview: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 0.7.2+1
  build_runner: 1.10.0

dependency_overrides:
  dartx: ^0.5.0
  path: ^1.6.4 # cf. https://github.com/hivedb/hive/issues/285#issuecomment-633815558

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see 
  # changes take effect.
  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to 
    # assets. Note: this doesn't work with subfolders. 
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - lib/routes/data/
    - res/images/
    - res/lottie/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp